sudo: false
language: python
python:
- 3.5
env:
  global:
  - TOXENV="py${PYTHON_VERSION//./}"
install:
- make install
- pip install coveralls
script:
- make lint
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: akariv
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: fUK/7GUs1PCMFASOxi/iWY57LfWKUivyT4r+5Gp2GaH8ytG1ux83xnSHO3e1Jrjgdak8VcV4vhwXkhU/Eno6xjHA+1G/jeIBytR9k4FKvH89gFX416/MhCxn1WMAX3AQzKqm3/gp4niI66TK/YUX526ZvCMh3EXQkC2jyctqz2A6pvleGegLNCDmRFKwgQgLNrEtDFbLwdVTqsQ+CSviEn5qFOaG8/Nh5KMYKMgCbIaJ83H1PklG7dKbFGn2aKqdvsC4uYtXbJxVkoW0D2afaM+xh1IEDz02TNzFBdAutC9qEVsbqX4TkyD6+m2x13Q8WnsCQPkEsPbZFpNDwhtUQyWr7rS+j7UxurYPTJQqZrt9AR1SSYbfgSvcmpILC+jnrxzxAa9HpleIMNLb/zgzC4ZFD75LBhWmiChPckU32/mZ7zrFveiNcMom6I+I+JPukbnhlvlOvxHQmRaQoIlkZeTmUAv7Z/Z6xz0h7WB8v/kZ+AhQq2UuXeE6tQaN//mEy5YwVKRHTexRRUnCtN2m50vaTwpvJzcQvdej8kybWtAITOA99e4vgUmoDDk/6rmzIfJP5o4ir+anTaE/kku8ay10ki3d3gr4+hk48aGoUKQFDXuWaAzf4mgu+lDPN9j3/RTIrysjwTtxMbQMAa3Kf15xoevyg2Kh0FdENgQ2u4s=
